# Generated by Django 3.2.25 on 2025-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bookings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.CharField(default='', max_length=300),
        ),
    ]
